import type { EventColorConfig } from "./types";

const EVENT_COLORS: Record<string, EventColorConfig> = {
  binder_received: {
    dotBg: "bg-primary-500",
    dotBorder: "border-primary-300",
    cardBorder: "border-r-primary-400",
    cardTint: "from-primary-50/60",
    badgeBg: "bg-primary-100",
    badgeText: "text-primary-700",
    chipActiveBg: "bg-primary-100",
    chipActiveText: "text-primary-800",
    chipActiveBorder: "border-primary-300",
    iconColor: "text-primary-600",
  },
  binder_returned: {
    dotBg: "bg-emerald-500",
    dotBorder: "border-emerald-300",
    cardBorder: "border-r-emerald-400",
    cardTint: "from-emerald-50/60",
    badgeBg: "bg-emerald-100",
    badgeText: "text-emerald-700",
    chipActiveBg: "bg-emerald-100",
    chipActiveText: "text-emerald-800",
    chipActiveBorder: "border-emerald-300",
    iconColor: "text-emerald-600",
  },
  binder_status_change: {
    dotBg: "bg-sky-500",
    dotBorder: "border-sky-300",
    cardBorder: "border-r-sky-400",
    cardTint: "from-sky-50/60",
    badgeBg: "bg-sky-100",
    badgeText: "text-sky-700",
    chipActiveBg: "bg-sky-100",
    chipActiveText: "text-sky-800",
    chipActiveBorder: "border-sky-300",
    iconColor: "text-sky-600",
  },
  invoice_created: {
    dotBg: "bg-violet-500",
    dotBorder: "border-violet-300",
    cardBorder: "border-r-violet-400",
    cardTint: "from-violet-50/60",
    badgeBg: "bg-violet-100",
    badgeText: "text-violet-700",
    chipActiveBg: "bg-violet-100",
    chipActiveText: "text-violet-800",
    chipActiveBorder: "border-violet-300",
    iconColor: "text-violet-600",
  },
  charge_created: {
    dotBg: "bg-amber-500",
    dotBorder: "border-amber-300",
    cardBorder: "border-r-amber-400",
    cardTint: "from-amber-50/60",
    badgeBg: "bg-amber-100",
    badgeText: "text-amber-700",
    chipActiveBg: "bg-amber-100",
    chipActiveText: "text-amber-800",
    chipActiveBorder: "border-amber-300",
    iconColor: "text-amber-600",
  },
  charge_issued: {
    dotBg: "bg-orange-500",
    dotBorder: "border-orange-300",
    cardBorder: "border-r-orange-400",
    cardTint: "from-orange-50/60",
    badgeBg: "bg-orange-100",
    badgeText: "text-orange-700",
    chipActiveBg: "bg-orange-100",
    chipActiveText: "text-orange-800",
    chipActiveBorder: "border-orange-300",
    iconColor: "text-orange-600",
  },
  charge_paid: {
    dotBg: "bg-green-500",
    dotBorder: "border-green-300",
    cardBorder: "border-r-green-400",
    cardTint: "from-green-50/60",
    badgeBg: "bg-green-100",
    badgeText: "text-green-700",
    chipActiveBg: "bg-green-100",
    chipActiveText: "text-green-800",
    chipActiveBorder: "border-green-300",
    iconColor: "text-green-600",
  },
  notification: {
    dotBg: "bg-rose-500",
    dotBorder: "border-rose-300",
    cardBorder: "border-r-rose-400",
    cardTint: "from-rose-50/60",
    badgeBg: "bg-rose-100",
    badgeText: "text-rose-700",
    chipActiveBg: "bg-rose-100",
    chipActiveText: "text-rose-800",
    chipActiveBorder: "border-rose-300",
    iconColor: "text-rose-600",
  },
};

EVENT_COLORS.notification_sent = EVENT_COLORS.notification;
EVENT_COLORS.client_created = {
  dotBg: "bg-primary-500",
  dotBorder: "border-primary-300",
  cardBorder: "border-r-primary-400",
  cardTint: "from-primary-50/60",
  badgeBg: "bg-primary-100",
  badgeText: "text-primary-700",
  chipActiveBg: "bg-primary-100",
  chipActiveText: "text-primary-800",
  chipActiveBorder: "border-primary-300",
  iconColor: "text-primary-600",
};
EVENT_COLORS.client_info_updated = {
  dotBg: "bg-sky-500",
  dotBorder: "border-sky-300",
  cardBorder: "border-r-sky-400",
  cardTint: "from-sky-50/60",
  badgeBg: "bg-sky-100",
  badgeText: "text-sky-700",
  chipActiveBg: "bg-sky-100",
  chipActiveText: "text-sky-800",
  chipActiveBorder: "border-sky-300",
  iconColor: "text-sky-600",
};
EVENT_COLORS.tax_profile_updated = {
  dotBg: "bg-slate-500",
  dotBorder: "border-slate-300",
  cardBorder: "border-r-slate-400",
  cardTint: "from-slate-50/60",
  badgeBg: "bg-slate-100",
  badgeText: "text-slate-700",
  chipActiveBg: "bg-slate-100",
  chipActiveText: "text-slate-800",
  chipActiveBorder: "border-slate-300",
  iconColor: "text-slate-600",
};
EVENT_COLORS.reminder_created = {
  dotBg: "bg-amber-500",
  dotBorder: "border-amber-300",
  cardBorder: "border-r-amber-400",
  cardTint: "from-amber-50/60",
  badgeBg: "bg-amber-100",
  badgeText: "text-amber-700",
  chipActiveBg: "bg-amber-100",
  chipActiveText: "text-amber-800",
  chipActiveBorder: "border-amber-300",
  iconColor: "text-amber-600",
};
EVENT_COLORS.document_uploaded = {
  dotBg: "bg-emerald-500",
  dotBorder: "border-emerald-300",
  cardBorder: "border-r-emerald-400",
  cardTint: "from-emerald-50/60",
  badgeBg: "bg-emerald-100",
  badgeText: "text-emerald-700",
  chipActiveBg: "bg-emerald-100",
  chipActiveText: "text-emerald-800",
  chipActiveBorder: "border-emerald-300",
  iconColor: "text-emerald-600",
};
EVENT_COLORS.signature_request_created = {
  dotBg: "bg-violet-500",
  dotBorder: "border-violet-300",
  cardBorder: "border-r-violet-400",
  cardTint: "from-violet-50/60",
  badgeBg: "bg-violet-100",
  badgeText: "text-violet-700",
  chipActiveBg: "bg-violet-100",
  chipActiveText: "text-violet-800",
  chipActiveBorder: "border-violet-300",
  iconColor: "text-violet-600",
};
EVENT_COLORS.invoice_attached = EVENT_COLORS.invoice_created;
EVENT_COLORS.tax_deadline_due = {
  dotBg: "bg-teal-500",
  dotBorder: "border-teal-300",
  cardBorder: "border-r-teal-400",
  cardTint: "from-teal-50/60",
  badgeBg: "bg-teal-100",
  badgeText: "text-teal-700",
  chipActiveBg: "bg-teal-100",
  chipActiveText: "text-teal-800",
  chipActiveBorder: "border-teal-300",
  iconColor: "text-teal-600",
};
EVENT_COLORS.annual_report_status_changed = {
  dotBg: "bg-indigo-500",
  dotBorder: "border-indigo-300",
  cardBorder: "border-r-indigo-400",
  cardTint: "from-indigo-50/60",
  badgeBg: "bg-indigo-100",
  badgeText: "text-indigo-700",
  chipActiveBg: "bg-indigo-100",
  chipActiveText: "text-indigo-800",
  chipActiveBorder: "border-indigo-300",
  iconColor: "text-indigo-600",
};

const DEFAULT_EVENT_COLOR: EventColorConfig = {
  dotBg: "bg-gray-400",
  dotBorder: "border-gray-300",
  cardBorder: "border-r-gray-300",
  cardTint: "from-gray-50/40",
  badgeBg: "bg-gray-100",
  badgeText: "text-gray-600",
  chipActiveBg: "bg-gray-100",
  chipActiveText: "text-gray-700",
  chipActiveBorder: "border-gray-300",
  iconColor: "text-gray-500",
};

export const getEventColor = (eventType: string): EventColorConfig =>
  EVENT_COLORS[eventType] ?? DEFAULT_EVENT_COLOR;
