export const ENDPOINTS = {
  health: "/health",
  info: "/info",
  authLogin: "/auth/login",
  authLogout: "/auth/logout",
  clients: "/clients",
  clientById: (clientId: number | string) => `/clients/${clientId}`,
  clientBinders: (clientId: number | string) => `/clients/${clientId}/binders`,
  clientTimeline: (clientId: number | string) =>
    `/clients/${clientId}/timeline`,
  binders: "/binders",
  binderById: (binderId: number | string) => `/binders/${binderId}`,
  binderReady: (binderId: number | string) => `/binders/${binderId}/ready`,
  binderReturn: (binderId: number | string) => `/binders/${binderId}/return`,
  binderReceive: "/binders/receive",
  binderHistory: (binderId: number | string) => `/binders/${binderId}/history`,
  bindersOpen: "/binders/open",
  dashboardSummary: "/dashboard/summary",
  dashboardOverview: "/dashboard/overview",
  dashboardWorkQueue: "/dashboard/work-queue",
  dashboardAttention: "/dashboard/attention",
  search: "/search",
  charges: "/charges",
  chargeById: (chargeId: number | string) => `/charges/${chargeId}`,
  chargeIssue: (chargeId: number | string) => `/charges/${chargeId}/issue`,
  chargeMarkPaid: (chargeId: number | string) =>
    `/charges/${chargeId}/mark-paid`,
  chargeCancel: (chargeId: number | string) => `/charges/${chargeId}/cancel`,
  documentsUpload: "/documents/upload",
  documentsByClient: (clientId: number | string) =>
    `/documents/client/${clientId}`,
  documentSignalsByClient: (clientId: number | string) =>
    `/documents/client/${clientId}/signals`,
  annualReports: "/annual-reports",
  annualReportById: (id: number | string) => `/annual-reports/${id}`,
  annualReportTransition: (id: number | string) =>
    `/annual-reports/${id}/transition`,
  annualReportSubmit: (id: number | string) => `/annual-reports/${id}/submit`,
  annualReportsKanban: "/annual-reports/kanban/view",
  annualReportAddSchedule: (id: number | string) =>
    `/annual-reports/${id}/schedules`,
  taxDeadlines: "/tax-deadlines",
  taxDeadlineById: (id: number | string) => `/tax-deadlines/${id}`,
  taxDeadlineComplete: (id: number | string) => `/tax-deadlines/${id}/complete`,
  taxDeadlinesDashboard: "/tax-deadlines/dashboard/urgent",
  clientAuthorityContacts: (clientId: number | string) =>
    `/clients/${clientId}/authority-contacts`,
  AUTHORITY_CONTACT_DETAIL: (id: number) =>
    `/clients/authority-contacts/${id}`,
  authorityContactById: (id: number | string) =>
    `/clients/authority-contacts/${id}`,
  clientTaxProfile: (clientId: number | string) =>
    `/clients/${clientId}/tax-profile`,
  clientSignatureRequests: (clientId: number | string) =>
    `/clients/${clientId}/signature-requests`,
  correspondenceList: (clientId: number | string) => `/clients/${clientId}/correspondence`,
  correspondenceCreate: (clientId: number | string) => `/clients/${clientId}/correspondence`,
  correspondenceById: (clientId: number | string, id: number | string) =>
    `/clients/${clientId}/correspondence/${id}`,
  clientsExport: "/clients/export",
  clientsTemplate: "/clients/template",
  clientsImport: "/clients/import",
  signatureRequests: "/signature-requests",
  signatureRequestsPending: "/signature-requests/pending",
  signatureRequestById: (id: number | string) => `/signature-requests/${id}`,
  signatureRequestSend: (id: number | string) =>
    `/signature-requests/${id}/send`,
  signatureRequestCancel: (id: number | string) =>
    `/signature-requests/${id}/cancel`,
  signatureRequestAuditTrail: (id: number | string) =>
    `/signature-requests/${id}/audit-trail`,
  users: "/users",
  userById: (id: number | string) => `/users/${id}`,
  userActivate: (id: number | string) => `/users/${id}/activate`,
  userDeactivate: (id: number | string) => `/users/${id}/deactivate`,
  userResetPassword: (id: number | string) => `/users/${id}/reset-password`,
  userAuditLogs: "/users/audit-logs",
  dashboardTaxSubmissions: "/dashboard/tax-submissions",
  reportsAging: "/reports/aging",
  reportsAgingExport: "/reports/aging/export",
  reminders: "/reminders",
  reminderById: (id: number) => `/reminders/${id}`,
  reminderCancel: (id: number) => `/reminders/${id}/cancel`,
  vatWorkItems: "/vat/work-items",
  vatWorkItemById: (id: number | string) => `/vat/work-items/${id}`,
  vatWorkItemsByClient: (clientId: number | string) => `/vat/clients/${clientId}/work-items`,
  vatWorkItemMaterialsComplete: (id: number | string) => `/vat/work-items/${id}/materials-complete`,
  vatWorkItemInvoices: (id: number | string) => `/vat/work-items/${id}/invoices`,
  vatWorkItemInvoiceById: (id: number | string, invoiceId: number | string) => `/vat/work-items/${id}/invoices/${invoiceId}`,
  vatWorkItemReadyForReview: (id: number | string) => `/vat/work-items/${id}/ready-for-review`,
  vatWorkItemSendBack: (id: number | string) => `/vat/work-items/${id}/send-back`,
  vatWorkItemFile: (id: number | string) => `/vat/work-items/${id}/file`,
  vatWorkItemAudit: (id: number | string) => `/vat/work-items/${id}/audit`,
  annualReportOverdue: "/annual-reports/overdue",
  annualReportTransitionStatus: (id: number | string) => `/annual-reports/${id}/status`,
  annualReportDeadline: (id: number | string) => `/annual-reports/${id}/deadline`,
  annualReportSchedules: (id: number | string) => `/annual-reports/${id}/schedules`,
  annualReportSchedulesComplete: (id: number | string) => `/annual-reports/${id}/schedules/complete`,
  annualReportHistory: (id: number | string) => `/annual-reports/${id}/history`,
  clientAnnualReports: (clientId: number | string) => `/clients/${clientId}/annual-reports`,
  taxYearSummary: (taxYear: number | string) => `/tax-year/${taxYear}/summary`,
  taxYearReports: (taxYear: number | string) => `/tax-year/${taxYear}/reports`,
  annualReportDetails: (id: number | string) => `/annual-reports/${id}/details`,
  advancePayments: "/advance-payments",
  advancePaymentById: (id: number | string) => `/advance-payments/${id}`,
  advancePaymentSuggest: "/advance-payments/suggest",
  advancePaymentsOverview: "/advance-payments/overview",
  vatClientSummary: (clientId: number | string) => `/vat/client/${clientId}/summary`,
  vatClientExport: (clientId: number | string) => `/vat/client/${clientId}/export`,
  clientStatusCard: (clientId: number | string) => `/clients/${clientId}/status-card`,
  documentById: (id: number | string) => `/documents/${id}`,
  documentReplace: (id: number | string) => `/documents/${id}/replace`,
  annualReportFinancials: (id: number | string) => `/annual-reports/${id}/financials`,
  annualReportReadiness: (id: number | string) => `/annual-reports/${id}/readiness`,
  annualReportIncome: (id: number | string) => `/annual-reports/${id}/income`,
  annualReportIncomeById: (id: number | string, lineId: number | string) =>
    `/annual-reports/${id}/income/${lineId}`,
  annualReportExpenses: (id: number | string) => `/annual-reports/${id}/expenses`,
  annualReportExpenseById: (id: number | string, lineId: number | string) =>
    `/annual-reports/${id}/expenses/${lineId}`,
  annualReportTaxCalculation: (id: number | string) => `/annual-reports/${id}/tax-calculation`,
  annualReportAdvancesSummary: (id: number | string) => `/annual-reports/${id}/advances-summary`,
  annualReportAnnex: (id: number | string, schedule: string) =>
    `/annual-reports/${id}/annex/${schedule}`,
  annualReportAnnexLine: (id: number | string, schedule: string, lineId: number | string) =>
    `/annual-reports/${id}/annex/${schedule}/${lineId}`,
  annualReportAmend: (id: number | string) => `/annual-reports/${id}/amend`,
  taxDeadlinesTimeline: "/tax-deadlines/timeline",
  advancePaymentsKPI: "/advance-payments/kpi",
  advancePaymentsChart: "/advance-payments/chart",
  notifications: "/notifications",
  notificationsUnreadCount: "/notifications/unread-count",
  notificationsMarkRead: "/notifications/mark-read",
  notificationsMarkAllRead: "/notifications/mark-all-read",
  documentDownloadUrl: (id: number | string) => `/documents/${id}/download-url`,
} as const;
