export const API_BASE_PATH = "/api/v1";

export const ENDPOINTS = {
  health: "/health",
  info: "/info",
  authLogin: "/auth/login",
  authLogout: "/auth/logout",
  clients: "/clients",
  clientById: (clientId: number | string) => `/clients/${clientId}`,
  clientBinders: (clientId: number | string) => `/clients/${clientId}/binders`,
  clientTimeline: (clientId: number | string) =>
    `/clients/${clientId}/timeline`,
  binders: "/binders",
  binderById: (binderId: number | string) => `/binders/${binderId}`,
  binderReady: (binderId: number | string) => `/binders/${binderId}/ready`,
  binderReturn: (binderId: number | string) => `/binders/${binderId}/return`,
  binderReceive: "/binders/receive",
  binderHistory: (binderId: number | string) => `/binders/${binderId}/history`,
  bindersOpen: "/binders/open",
  dashboardSummary: "/dashboard/summary",
  dashboardOverview: "/dashboard/overview",
  dashboardWorkQueue: "/dashboard/work-queue",
  dashboardAttention: "/dashboard/attention",
  search: "/search",
  charges: "/charges",
  chargeById: (chargeId: number | string) => `/charges/${chargeId}`,
  chargeIssue: (chargeId: number | string) => `/charges/${chargeId}/issue`,
  chargeMarkPaid: (chargeId: number | string) =>
    `/charges/${chargeId}/mark-paid`,
  chargeCancel: (chargeId: number | string) => `/charges/${chargeId}/cancel`,
  documentsUpload: "/documents/upload",
  documentsByClient: (clientId: number | string) =>
    `/documents/client/${clientId}`,
  documentSignalsByClient: (clientId: number | string) =>
    `/documents/client/${clientId}/signals`,
  annualReports: "/annual-reports",
  annualReportById: (id: number | string) => `/annual-reports/${id}`,
  annualReportTransition: (id: number | string) =>
    `/annual-reports/${id}/transition`,
  annualReportSubmit: (id: number | string) => `/annual-reports/${id}/submit`,
  annualReportsKanban: "/annual-reports/kanban/view",
  annualReportAddSchedule: (id: number | string) =>
    `/annual-reports/${id}/schedules`,
  taxDeadlines: "/tax-deadlines",
  taxDeadlineById: (id: number | string) => `/tax-deadlines/${id}`,
  taxDeadlineComplete: (id: number | string) => `/tax-deadlines/${id}/complete`,
  taxDeadlinesDashboard: "/tax-deadlines/dashboard/urgent",
  clientAuthorityContacts: (clientId: number | string) =>
    `/clients/${clientId}/authority-contacts`,
  authorityContactById: (id: number | string) =>
    `/clients/authority-contacts/${id}`,
  clientTaxProfile: (clientId: number | string) =>
    `/clients/${clientId}/tax-profile`,
  clientSignatureRequests: (clientId: number | string) =>
    `/clients/${clientId}/signature-requests`,
  correspondenceList: (clientId: number | string) => `/clients/${clientId}/correspondence`,
  correspondenceCreate: (clientId: number | string) => `/clients/${clientId}/correspondence`,
  clientsExport: "/clients/export",
  clientsTemplate: "/clients/template",
  clientsImport: "/clients/import",
  signatureRequests: "/signature-requests",
  signatureRequestsPending: "/signature-requests/pending",
  signatureRequestById: (id: number | string) => `/signature-requests/${id}`,
  signatureRequestSend: (id: number | string) =>
    `/signature-requests/${id}/send`,
  signatureRequestCancel: (id: number | string) =>
    `/signature-requests/${id}/cancel`,
  signatureRequestAuditTrail: (id: number | string) =>
    `/signature-requests/${id}/audit-trail`,
  users: "/users",
  userById: (id: number | string) => `/users/${id}`,
  userActivate: (id: number | string) => `/users/${id}/activate`,
  userDeactivate: (id: number | string) => `/users/${id}/deactivate`,
  userResetPassword: (id: number | string) => `/users/${id}/reset-password`,
  dashboardTaxSubmissions: "/dashboard/tax-submissions",
  reportsAging: "/reports/aging",
  reportsAgingExport: "/reports/aging/export",
  reminders: "/reminders",
  reminderById: (id: number) => `/reminders/${id}`,
  reminderCancel: (id: number) => `/reminders/${id}/cancel`,
  reminderMarkSent: (id: number) => `/reminders/${id}/mark-sent`,
  vatWorkItems: "/vat/work-items",
  vatWorkItemById: (id: number | string) => `/vat/work-items/${id}`,
  vatWorkItemsByClient: (clientId: number | string) => `/vat/clients/${clientId}/work-items`,
  vatWorkItemMaterialsComplete: (id: number | string) => `/vat/work-items/${id}/materials-complete`,
  vatWorkItemInvoices: (id: number | string) => `/vat/work-items/${id}/invoices`,
  vatWorkItemInvoiceById: (id: number | string, invoiceId: number | string) => `/vat/work-items/${id}/invoices/${invoiceId}`,
  vatWorkItemReadyForReview: (id: number | string) => `/vat/work-items/${id}/ready-for-review`,
  vatWorkItemSendBack: (id: number | string) => `/vat/work-items/${id}/send-back`,
  vatWorkItemFile: (id: number | string) => `/vat/work-items/${id}/file`,
  vatWorkItemAudit: (id: number | string) => `/vat/work-items/${id}/audit`,
  annualReportOverdue: "/annual-reports/overdue",
  annualReportTransitionStatus: (id: number | string) => `/annual-reports/${id}/status`,
  annualReportDeadline: (id: number | string) => `/annual-reports/${id}/deadline`,
  annualReportSchedules: (id: number | string) => `/annual-reports/${id}/schedules`,
  annualReportSchedulesComplete: (id: number | string) => `/annual-reports/${id}/schedules/complete`,
  annualReportHistory: (id: number | string) => `/annual-reports/${id}/history`,
  clientAnnualReports: (clientId: number | string) => `/clients/${clientId}/annual-reports`,
  taxYearSummary: (taxYear: number | string) => `/tax-year/${taxYear}/summary`,
  taxYearReports: (taxYear: number | string) => `/tax-year/${taxYear}/reports`,
  annualReportDetails: (id: number | string) => `/annual-reports/${id}/details`,
} as const;
